---
# https://github.com/ibiqlik/action-yamllint
name: YAML Lint

on:
  push:
    paths:
      - '**.yml'
      - '**.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
